wandb: True
encoder_trainable: false
trainer:
  n_frames: null
  training:
    learning_rate: 1e-4
    weight_decay: 0.00
    num_workers: 8
    batch_size_per_gpu: 128
    gradient_accumulation_steps: 1
    find_unused_parameters: true
    mixed_precision: fp16
    max_grad_norm: null
    max_grad_value: null
    epochs: 20
    embedding_norm: null
    loss: l1
    heatmap_loss: cross_entropy
    save_every: 1
    checkpoint_dir: checkpoints
    normalized_coordinates: false
  evaluation:
    batch_size_per_gpu: 128
    eval_every: 1
    eval_first: true
model:
  type: locator
  num_context_latents: null
  num_target_latents: null
  predictor:
    heatmap_hidden_dim: 256
