_wandb:
    value:
        cli_version: 0.21.3
        e:
            uvr7fklgw3x13v9igvk430sy49rncguh:
                args:
                    - --config_path
                    - configs/vjepa2_kinetics_400.yaml
                cpu_count: 40
                cpu_count_logical: 80
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "250374057984"
                        used: "124596547584"
                email: francois_porcher@berkeley.edu
                executable: /private/home/francoisporcher/.conda/envs/future_latents/bin/python3.10
                git:
                    commit: 86eb148267d382e5812f3c89dd0a8f374699ccb8
                    remote: git@github.com:FrancoisPorcher/FutureLatents.git
                gpu: Quadro GV100
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Quadro GV100
                      uuid: GPU-2ff3644f-6e25-d962-9b9d-4f1452e70e58
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Quadro GV100
                      uuid: GPU-a3a74c53-c1cd-3fd5-ffff-ea2f3c28ea35
                host: devfair0607
                memory:
                    total: "810160443392"
                os: Linux-5.15.0-1061-nvidia-x86_64-with-glibc2.35
                program: -m src.main
                python: CPython 3.10.18
                root: /private/home/francoisporcher/FutureLatents
                startedAt: "2025-09-04T12:10:06.419240Z"
                writerId: uvr7fklgw3x13v9igvk430sy49rncguh
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "3":
                - 1
            "4": 3.10.18
            "5": 0.21.3
            "6": 4.55.4
            "12": 0.21.3
            "13": linux-x86_64
