datasets:
  kinetics_400:
    n_frame: 64
    stride: 2
    paths:
      train_csv: /checkpoint/abardes/datasets/Kinetics400/annotations/k400_train_paths.csv
      val_csv: /checkpoint/abardes/datasets/Kinetics400/annotations/k400_val_paths.csv
