datasets:
  train:
    name: kinetics_400
    kinetics_400:
      n_frame: ${TRAINER.N_FRAMES}
      stride: 2
      paths:
        csv: /checkpoint/abardes/datasets/Kinetics400/annotations/k400_train_paths.csv
        labels_txt: /checkpoint/abardes/datasets/Kinetics400/annotations/k400_labels.txt
  val:
    name: kinetics_400
    kinetics_400:
      n_frame: ${TRAINER.N_FRAMES}
      stride: 2
      paths:
        csv: /checkpoint/abardes/datasets/Kinetics400/annotations/k400_val_paths.csv
        labels_txt: /checkpoint/abardes/datasets/Kinetics400/annotations/k400_labels.txt
