datasets:
  train:
    name: kinetics_400_cached
    kinetics_400_cached:
      path_col: out_path
      paths:
        metadata: /private/home/francoisporcher/kinetics_400_embeddings_vjepa2_vitl_fpc64_256/manifest.csv
  val:
    name: kinetics_400_cached
    kinetics_400_cached:
      path_col: out_path
      paths:
        metadata: /private/home/francoisporcher/kinetics_400_embeddings_vjepa2_vitl_fpc64_256/manifest.csv
